# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."arcane" = {
    image = "ghcr.io/getarcaneapp/manager:latest";
    environment = {
      "APP_URL" = "http://localhost:3552";
      # Fill these in otherwise Arcane will not start
      "ENCRYPTION_KEY" = ""; # This will be empty in the git repo, replace the compose with the ENCRYPTION_KEY
      "JWT_SECRET" = ""; # Same as above for the JWT_SECRET
      # I will make these in .env files later i am just lazy
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/DATA/AppData/arcane:/app/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "3552:3552/tcp"
    ];
    cmd = [  ];
    labels = {
      "icon" = "https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/arcane-light.svg";
    };
    log-driver = "journald";
    extraOptions = [
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--hostname=arcane"
      "--memory=3436183552b"
      "--network-alias=arcane"
      "--network=arcanemanager_arcane-manager"
    ];
  };
  systemd.services."docker-arcane" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-arcanemanager_arcane-manager.service"
    ];
    requires = [
      "docker-network-arcanemanager_arcane-manager.service"
    ];
    partOf = [
      "docker-compose-arcanemanager-root.target"
    ];
    wantedBy = [
      "docker-compose-arcanemanager-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-arcanemanager_arcane-manager" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f arcanemanager_arcane-manager";
    };
    script = ''
      docker network inspect arcanemanager_arcane-manager || docker network create arcanemanager_arcane-manager --driver=bridge
    '';
    partOf = [ "docker-compose-arcanemanager-root.target" ];
    wantedBy = [ "docker-compose-arcanemanager-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-arcanemanager-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
