# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."arcane" = {
    image = "ghcr.io/getarcaneapp/manager:latest";
    environment = {
      "APP_URL" = "http://localhost:3552";
      "ENCRYPTION_KEY" = "";
      "JWT_SECRET" = "";
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/DATA/AppData/arcane:/app/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "3552:3552/tcp"
    ];
    cmd = [  ];
    labels = {
      "icon" = "https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/arcane-light.svg";
    };
    log-driver = "journald";
    extraOptions = [
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--hostname=arcane"
      "--memory=3436183552b"
      "--network=host"
    ];
  };
  systemd.services."podman-arcane" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arcane-manager-single-root.target"
    ];
    wantedBy = [
      "podman-compose-arcane-manager-single-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-arcane-manager-single-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
