# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."homeassistant" = {
    image = "homeassistant/home-assistant:2025.11";
    environment = {
      "OPENAI_API_KEY" = "sk-xxxxxx";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/DATA/AppData/homeassistant/config:/config:rw"
      "/etc/localtime:/etc/localtime:ro"
      "/run/dbus:/run/dbus:ro"
    ];
    labels = {
      "com.docker.compose.config-hash" = "bc06b6ae2d7e0553b5a712d4227dd13e6b63bc8dbe00b904c469e494a5ebace0";
      "com.docker.compose.container-number" = "1";
      "com.docker.compose.depends_on" = "";
      "com.docker.compose.image" = "sha256:f971850a6ec1fb5c5fd4e1748058e9e1f589aaf0da933b8d88bb5dee03f5b5e8";
      "com.docker.compose.oneoff" = "False";
      "com.docker.compose.project" = "homeassistant";
      "com.docker.compose.project.config_files" = "/var/lib/casaos/apps/homeassistant/docker-compose.yml";
      "com.docker.compose.project.working_dir" = "/var/lib/casaos/apps/homeassistant";
      "com.docker.compose.service" = "homeassistant";
      "com.docker.compose.version" = "";
      "icon" = "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/HomeAssistant/icon.png";
    };
    log-driver = "journald";
    extraOptions = [
      "--hostname=wisteria-lab"
      "--memory-reservation=268435456b"
      "--network=host"
      "--privileged"
      "--runtime=runc"
    ];
  };
  systemd.services."docker-homeassistant" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-home-assistant-root.target"
    ];
    wantedBy = [
      "docker-compose-home-assistant-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-home-assistant-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
