# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."pihole" = {
    image = "docker.io/pihole/pihole:latest";
    environment = {
      "FTLCONF_LOCAL_IPV4" = "";
      "FTLCONF_dns_listeningMode" = "ALL";
      "FTLCONF_webserver_api_password" = "";
      "FTLCONF_webserver_port" = "8080";
      "PIHOLE_GID" = "0";
      "PIHOLE_UID" = "0";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/DATA/AppData/pihole-single/pihole:/etc/pihole:rw"
      "/DATA/AppData/pihole-single/pihole/dnsmasq:/etc/dnsmasq.d:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--network=host"
    ];
  };
  systemd.services."podman-pihole" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-pihole-root.target"
    ];
    wantedBy = [
      "podman-compose-pihole-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-pihole-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
