# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."pihole" = {
    image = "pihole/pihole:latest";
    environmentFiles = [ "/var/lib/pihole/.env" ];
    environment = {
      #"FTLCONF_LOCAL_IPV4" = ""; # provided by the .env
      "FTLCONF_dns_listeningMode" = "ALL";
      #"FTLCONF_webserver_api_password" = ""; # provided by the .env
      "FTLCONF_webserver_port" = "8080";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/DATA/AppData/pihole-stack/pihole:/etc/pihole:rw"
      "/DATA/AppData/pihole-stack/pihole/dnsmasq:/etc/dnsmasq.d:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--network=host"
    ];
  };
  systemd.services."docker-pihole" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-pihole-root.target"
    ];
    wantedBy = [
      "docker-compose-pihole-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-pihole-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
